name: CI

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:

jobs:
  matrix-coverage:
    uses: scikit-package/release-scripts/.github/workflows/_matrix-and-codecov-on-merge-to-main.yml@v0
    with:
      project: diffpy.cmi
      c_extension: false
      headless: false
      run: |
        echo "Running tests for diffpy.cmi"
        cmi install _tests
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
